<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MatchingEngine.Engine-cfeb4fb1-c163-404c-a5cf-895805bfb3a8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\MatchingEngine.Kafka\MatchingEngine.Kafka.csproj" />
    <ProjectReference Include="..\..\..\Shared\MatchingEngine.Core\MatchingEngine.Core.csproj" />
  </ItemGroup>
</Project>
